-- 코드를 입력하세요
SELECT DISTINCT R.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR R, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE R.CAR_ID = H.CAR_ID AND R.CAR_TYPE = '세단' AND H.START_DATE LIKE '%-10-%'
ORDER BY CAR_ID DESC;