WITH AVAILABILITY_TABLE AS
(SELECT DISTINCT R.CAR_ID 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
WHERE R.START_DATE <= '2022-10-16' AND R.END_DATE >= '2022-10-16')

SELECT DISTINCT CAR_ID,
IF(CAR_ID IN (SELECT CAR_ID FROM AVAILABILITY_TABLE), '대여중', '대여 가능')
AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC;
