-- 코드를 입력하세요
SELECT u.USER_ID AS USER_ID, u.NICKNAME AS NICKNAME, CONCAT(CITY," ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소, CONCAT(LEFT(u.TLNO,3), "-", MID(u.TLNO,4, 4), '-', RIGHT(u.TLNO, 4)) as 전화번호
FROM USED_GOODS_BOARD b, USED_GOODS_USER u
WHERE u.USER_ID = b.WRITER_ID
GROUP BY b.WRITER_ID
HAVING COUNT(b.BOARD_ID) >= 3
ORDER BY u.USER_ID DESC