SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (T.MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA, (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) T
WHERE YEAR(DIFFERENTIATION_DATE) = T.YEAR
ORDER BY 1, 2;
