-- 코드를 입력하세요
WITH A AS (
    SELECT *
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
), B AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM A
    GROUP BY PRODUCT_ID
)

SELECT B.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE * B.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;