-- ROUND(숫자,반올림할 자릿수) - 숫자를 반올림할 자릿수 +1 자릿수에서 반올림
-- 서브쿼리 사용 : FROM 절에서 사용할 경우 테이블 명 명시해야함. 
SELECT REST_INFO.REST_ID as REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO, (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) as SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) as REST_REVIEW_2
WHERE REST_INFO.REST_ID = REST_REVIEW_2.REST_ID
AND ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, FAVORITES DESC;