WITH DURATION_TABLE AS
(SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION, 
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        ELSE ""
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)

SELECT D.HISTORY_ID AS HISTORY_ID, ROUND(C.DAILY_FEE * D.DURATION * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM DURATION_TABLE D 
LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = D.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND D.DURATION_TYPE = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭' 
ORDER BY FEE DESC, HISTORY_ID DESC;