WITH DISCOUNT_RATE_TABLE AS
(SELECT CAR_TYPE, TRIM(TRAILING '%' FROM DISCOUNT_RATE) AS DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE LIKE '30%'), 
FEE_TABLE AS
(SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C, DISCOUNT_RATE_TABLE D
WHERE C.CAR_TYPE = D.CAR_TYPE)

SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, F.FEE
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H, FEE_TABLE F
WHERE (C.CAR_ID = H.CAR_ID AND C.CAR_ID = F.CAR_ID)
AND (C.CAR_TYPE IN ('세단','SUV')) 
AND C.CAR_ID NOT IN (SELECT HH.CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HH
    WHERE HH.START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
    OR HH.END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
    OR (HH.START_DATE <= '2022-11-01' AND HH.END_DATE >= '2022-11-30'))
AND (F.FEE >= 500000 AND F.FEE < 2000000)
ORDER BY F.FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
